const eventosPadrao = [
  {
    id: 1,
    title: 'Atendimento Individual – João',
    start: new Date(2024, 5, 3, 9, 0),
    end: new Date(2024, 5, 3, 10, 0),
    desc: 'Sessão de acompanhamento com aluno João',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 2,
    title: 'Atendimento Individual – Ana',
    start: new Date(2024, 5, 3, 10, 15),
    end: new Date(2024, 5, 3, 11, 15),
    desc: 'Sessão de reforço de leitura e escrita',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 3,
    title: 'Atendimento em Grupo – 3º ano A',
    start: new Date(2024, 5, 4, 14, 0),
    end: new Date(2024, 5, 4, 15, 0),
    desc: 'Dinâmica para desenvolvimento de habilidades socioemocionais',
    color: '#2196f3',
    tipo: 'Atendimento em Grupo',
  },
  {
    id: 4,
    title: 'Reunião com Pais – Lucas',
    start: new Date(2024, 5, 5, 17, 0),
    end: new Date(2024, 5, 5, 17, 45),
    desc: 'Devolutiva dos atendimentos realizados com Lucas',
    color: '#ff9800',
    tipo: 'Reunião com Pais',
  },
  {
    id: 5,
    title: 'Avaliação Diagnóstica – Maria',
    start: new Date(2024, 5, 6, 8, 30),
    end: new Date(2024, 5, 6, 10, 0),
    desc: 'Aplicação de testes para avaliação do desenvolvimento cognitivo',
    color: '#9c27b0',
    tipo: 'Avaliação',
  },
  {
    id: 6,
    title: 'Capacitação Interna – TDAH e estratégias',
    start: new Date(2024, 5, 7, 13, 30),
    end: new Date(2024, 5, 7, 16, 0),
    desc: 'Formação interna com equipe pedagógica',
    color: '#607d8b',
    tipo: 'Capacitação',
  },
  {
    id: 7,
    title: 'Planejamento Semanal',
    start: new Date(2024, 5, 10, 8, 0),
    end: new Date(2024, 5, 10, 9, 0),
    desc: 'Organização dos atendimentos e relatórios da semana',
    color: '#795548',
    tipo: 'Planejamento',
  },
  {
    id: 8,
    title: 'Devolutiva com Equipe Pedagógica – Pedro',
    start: new Date(2024, 5, 11, 16, 0),
    end: new Date(2024, 5, 11, 16, 45),
    desc: 'Discussão de estratégias de acompanhamento com professores',
    color: '#ff5722',
    tipo: 'Devolutiva',
  },
  {
    id: 9,
    title: 'Atendimento Individual – Lara',
    start: new Date(2024, 5, 12, 11, 0),
    end: new Date(2024, 5, 12, 12, 0),
    desc: 'Sessão de apoio emocional e organização de rotina',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 10,
    title: 'Atendimento em Grupo – 4º ano B',
    start: new Date(2024, 5, 13, 15, 0),
    end: new Date(2024, 5, 13, 16, 0),
    desc: 'Trabalho com habilidades sociais e resolução de conflitos',
    color: '#2196f3',
    tipo: 'Atendimento em Grupo',
  },
  {
    id: 11,
    title: 'Reunião com Coordenação',
    start: new Date(2024, 5, 14, 10, 0),
    end: new Date(2024, 5, 14, 11, 0),
    desc: 'Alinhamento das demandas psicopedagógicas',
    color: '#03a9f4',
    tipo: 'Reunião',
  },
  {
    id: 12,
    title: 'Supervisão de Caso – Julia',
    start: new Date(2024, 5, 17, 14, 30),
    end: new Date(2024, 5, 17, 16, 0),
    desc: 'Análise de caso com equipe técnica externa',
    color: '#673ab7',
    tipo: 'Supervisão',
  },
  {
    id: 13,
    title: 'Palestra para Responsáveis – Inclusão Escolar',
    start: new Date(2024, 5, 18, 18, 0),
    end: new Date(2024, 5, 18, 19, 30),
    desc: 'Orientações para famílias sobre inclusão e desenvolvimento',
    color: '#e91e63',
    tipo: 'Palestra',
  },
  {
    id: 14,
    title: 'Relatórios Mensais',
    start: new Date(2024, 5, 20, 13, 0),
    end: new Date(2024, 5, 20, 17, 0),
    desc: 'Preenchimento de relatórios dos alunos atendidos',
    color: '#9e9e9e',
    tipo: 'Planejamento',
  },
   {
    id: 15,
    title: 'Atendimento Individual – Bruno',
    start: new Date(2024, 5, 21, 9, 0),
    end: new Date(2024, 5, 21, 10, 0),
    desc: 'Trabalho de organização da rotina e atenção',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 16,
    title: 'Atendimento Individual – Sofia',
    start: new Date(2024, 5, 21, 10, 15),
    end: new Date(2024, 5, 21, 11, 15),
    desc: 'Reforço de leitura e habilidades fonológicas',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 17,
    title: 'Atendimento Individual – Miguel',
    start: new Date(2024, 5, 22, 13, 30),
    end: new Date(2024, 5, 22, 14, 30),
    desc: 'Atividades para desenvolver memória de trabalho',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 18,
    title: 'Atendimento Individual – Alice',
    start: new Date(2024, 5, 22, 14, 45),
    end: new Date(2024, 5, 22, 15, 45),
    desc: 'Desenvolvimento de estratégias de autorregulação',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 19,
    title: 'Atendimento em Grupo – Autoconhecimento',
    start: new Date(2024, 5, 23, 9, 0),
    end: new Date(2024, 5, 23, 10, 30),
    desc: 'Grupo terapêutico para alunos do 6º ano',
    color: '#2196f3',
    tipo: 'Atendimento em Grupo',
  },
  {
    id: 20,
    title: 'Atendimento Individual – Rafael',
    start: new Date(2024, 5, 24, 11, 0),
    end: new Date(2024, 5, 24, 12, 0),
    desc: 'Trabalho com sequência lógica e raciocínio',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 21,
    title: 'Avaliação Cognitiva – Gabriel',
    start: new Date(2024, 5, 25, 8, 30),
    end: new Date(2024, 5, 25, 10, 0),
    desc: 'Aplicação de testes de desempenho cognitivo',
    color: '#9c27b0',
    tipo: 'Avaliação',
  },
  {
    id: 22,
    title: 'Atendimento Individual – Isabella',
    start: new Date(2024, 5, 26, 15, 0),
    end: new Date(2024, 5, 26, 16, 0),
    desc: 'Sessão de apoio emocional e escuta ativa',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 23,
    title: 'Devolutiva com Pais – Miguel',
    start: new Date(2024, 5, 27, 17, 0),
    end: new Date(2024, 5, 27, 17, 45),
    desc: 'Retorno sobre progresso no acompanhamento',
    color: '#ff9800',
    tipo: 'Reunião com Pais',
  },
  {
    id: 24,
    title: 'Atendimento Individual – Beatriz',
    start: new Date(2024, 5, 28, 9, 0),
    end: new Date(2024, 5, 28, 10, 0),
    desc: 'Intervenções para concentração e planejamento',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 25,
    title: 'Atendimento em Grupo – 2º ano B',
    start: new Date(2024, 5, 28, 14, 0),
    end: new Date(2024, 5, 28, 15, 0),
    desc: 'Atividade em grupo sobre cooperação e respeito',
    color: '#2196f3',
    tipo: 'Atendimento em Grupo',
  },
  {
    id: 26,
    title: 'Atendimento Individual – Enzo',
    start: new Date(2024, 6, 1, 10, 15),
    end: new Date(2024, 6, 1, 11, 15),
    desc: 'Trabalho com leitura funcional e inferência',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 27,
    title: 'Avaliação – Rafaela',
    start: new Date(2024, 6, 2, 8, 30),
    end: new Date(2024, 6, 2, 10, 0),
    desc: 'Aplicação de testes de compreensão auditiva',
    color: '#9c27b0',
    tipo: 'Avaliação',
  },
  {
    id: 28,
    title: 'Atendimento Individual – Otávio',
    start: new Date(2024, 6, 2, 11, 0),
    end: new Date(2024, 6, 2, 12, 0),
    desc: 'Desenvolvimento de habilidades sociais',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 29,
    title: 'Devolutiva com Família – Beatriz',
    start: new Date(2024, 6, 3, 17, 0),
    end: new Date(2024, 6, 3, 17, 45),
    desc: 'Discussão dos resultados da avaliação',
    color: '#ff9800',
    tipo: 'Reunião com Pais',
  },
  {
    id: 30,
    title: 'Atendimento Individual – Henrique',
    start: new Date(2024, 6, 4, 13, 30),
    end: new Date(2024, 6, 4, 14, 30),
    desc: 'Apoio para desenvolvimento da linguagem escrita',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 31,
    title: 'Grupo Terapêutico – Adolescência e Emoções',
    start: new Date(2024, 6, 5, 15, 0),
    end: new Date(2024, 6, 5, 16, 30),
    desc: 'Roda de conversa com alunos do 9º ano',
    color: '#2196f3',
    tipo: 'Atendimento em Grupo',
  },
  {
    id: 32,
    title: 'Atendimento Individual – Luana',
    start: new Date(2024, 6, 6, 10, 0),
    end: new Date(2024, 6, 6, 11, 0),
    desc: 'Planejamento de estudos e organização de tarefas',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
  {
    id: 33,
    title: 'Sessão de Avaliação – Rodrigo',
    start: new Date(2024, 6, 7, 9, 0),
    end: new Date(2024, 6, 7, 10, 30),
    desc: 'Avaliação de leitura e escrita funcional',
    color: '#9c27b0',
    tipo: 'Avaliação',
  },
  {
    id: 34,
    title: 'Atendimento Individual – Emanuel',
    start: new Date(2024, 6, 8, 11, 30),
    end: new Date(2024, 6, 8, 12, 30),
    desc: 'Trabalho de coordenação motora fina com atividades lúdicas',
    color: '#4caf50',
    tipo: 'Atendimento Individual',
  },
];

export default eventosPadrao;
